.vscode/launch.json

Related to: https://github.com/microsoft/vscode/issues/102042#issuecomment-656402933
This quick fix makes it possible to debug Typescript tests in VSCode, something I was working on. Hopefully this will make it easier for anyone else debugging their code to not run into the errors I've come across.

'resolveSourceMapLocations' bug in VSCode

---

src/k8s.test.ts
src/k8s.ts
src/tasks/harbor/harbor.ts

Creating a Harbor robot account for each team with push credentials for team member to download

feat: create robot accounts with push creds for teams

---

package-lock.json
package.json
src/tasks/gitea/gitea-drone-oauth.ts

This PR is updating the gitea client to version 1.19.1 so it matches the current gitea version (see #[1096](https://github.com/redkubes/otomi-core/pull/1096))
This PR also solves bug #[1101](https://github.com/redkubes/otomi-core/issues/1101)

fix: updated gitea client and updated ouath2 creation function

---

README.md
src/tasks/keycloak/keycloak.ts
src/validators.ts

Ticket regarding this issue: https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/otomi-core/1093
This PR changes the keycloak Realm User access token to 8 hours. This is not a fix for the issue but it will mitigate the amount of times that people will come across the issue.

feat: changed ttl for keycloak access token

---

.github/workflows/main.yaml
.github/workflows/pr-lint.yml

This PR updates some of the remaining deprecated GitHub Actions in Otomi-Tasks.
https://github.com/redkubes/otomi-core/issues/997
The Lint will still show a warning but that is because it doesn't use the newest version yet for this PR.

fix: update deprecated actions

---

package.json
src/tasks/otomi/copy-certs-argo.ts

For the argo auto image updater to work, a pull secret for the team repositories in Harbor needs to be in the argocd namespace. This new task `copy-certs-argo` copies all the `kubernetes.io/dockerconfigjson` secrets from the team namespaces to the argocd namespace. Te filter needs to be optimised so only the `harbor-pullsecret` secrets are copied.
The job for this task is already in core.
This is a temporary solution until an operator will take care of this.

feat: copy certs to argo ns for auto image updater

---

src/tasks/gitea/gitea.ts

This PR changes the access rights of the Otomi-Viewer team.
Otomi-Viewer team no longer has read access for all repos.
Otomi-Viewer team only has read access to otomi/values repo.
[See issue](https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/674)

feat: otomi viewer rights

---

src/tasks/gitea/gitea.ts

https://app.zenhub.com/workspaces/dev-5e7e84dddc966f05a627a19b/issues/gh/redkubes/unassigned-issues/654
This PR adds a feature to create gitea otomi charts repository.
Is paired with: https://github.com/redkubes/otomi-core/pull/1333
Added upsertRepo function call to create gitea otomi charts repository

feat: gitea otomi charts repo

---

src/operator/gitea.ts

This PR removes the stdout from the exec command so that certain data is not shown anymore, also added a log to see the changes to the group mapping.

fix: removes stdout add log for what is added

---

src/tasks/keycloak/keycloak.ts
src/validators.ts

This PR sets the offline keycloak token to 7 days.

fix: set the offline session to seven days

---

.github/workflows/main.yaml

https://jira.linode.com/browse/APL-135
This PR updates main github workflow to push `apl-tasks` image to the linode docker hub.
https://hub.docker.com/repository/docker/linode/apl-tasks/general
Is paired with: https://github.com/linode/apl-core/pull/1677

feat: linode dockerhub apl-tasks

---

src/operator/gitea.ts

See: [APL-204](https://jira.linode.com/browse/APL-204)
This fixes the Gitea oidc login 500 error, which happens because the group mapping is not formatted correctly

fix: group mapping for gitea oidc

---

src/operator/harbor.ts

This PR fixes the type errors that were present because the api was not always instantiated before it was being used.
See: [APL-160](https://jira.linode.com/browse/APL-160)

fix: check if setup was a success

---

src/operator/gitea.ts

A user that belongs to platform-admin group should be an admin admin in gitea app. This PR aims to meet that requirement.

fix: use platform-admin group to map admin role in gitea

---

src/operator/gitea.test.ts
src/operator/gitea.ts
src/tasks/common.ts

This PR fixes group team mappings and assign `platform-admin` users as an owner in the `otomi` organization. It also allows `platform-admin` users to view the dashboard and repositories (see screenshots below).

fix: platform admin

---

src/operator/harbor.ts

don't remove and recreate secret each time the operator is called

fix: harbor operator

---

src/k8s.ts
src/operator/harbor.ts

Fixes the bug in the operator that creates a robot account. Robot accounts in Harbor have prefixes with the default being `harbor$`. In the operator we configure it to be `otomi-`. But the configuration, due to a race condition, is applied after the first robot account is created. So it gets the `harbor$` prefix. This results in that the operator tries to re-create this robot account as it cannot find that it exist but when we create it Harbor response with robot account already exists. 
And 
Fixes the secret harbor-robot-admin where the name is wrong

fix: check if robot  already exists and re-create secret if robot name is wrong

---

package.json
src/operator/keycloak.test.ts
src/operator/keycloak.ts
src/tasks/keycloak/errors.ts
src/utils.test.ts
src/utils.ts

This PR replaces all instances of `utils.doApiCall`, which adds errors to a list but never raises them. This causes rejected requests to external APIs to get logged, but never retried. As a consequence, the operator will on a temporary failure (e.g. connection glitch) never reconcile fully until it is restarted.
The only additional functionality of this function wrapper is that it passes over 409 errors (conflict) which might not be the most sensible thing to do in all situations. Where appropriate, the retry after a failed request (i.e. due to a race condition of two operator instances) with this particular error should come to the same result – otherwise it is more likely that the operator needs to be refined for such cases instead of suppressing the error.
For reducing the chance of …

fix: fail on request errors for triggering retry

---

src/operator/gitea.test.ts
src/operator/gitea.ts

This PR adds the team- prefix to organizations to be inline with harbor teams.
Also updated the owners to Owners

fix: apl-430 with prefix

---

src/operator/gitea.ts

This PR changes the behavior of the Gitea operator so that it also ensures existence of the `team-admin` organization and creates a repository to deploy manifests through ArgoCD.
Error handling has been changed to raise exceptions directly (since any errors eventually lead to calling `exit` anyway).

fix: upsert admin team and create repo

---

package-lock.json
package.json
src/operator/gitea.ts

This PR updates the method for executing commands directly in the Gitea pod. The Gitea Helm chart in recent versions uses Deployment instead of a StatefulSet, which requires looking up the Gitea pod by selectors instead of using a hard-coded name.
The code changes itself should work both on the current Core `main` as well as the feature branch. However, the pod permissions need to be updated, which is implemented in the feature branch only.
Core PR: https://github.com/linode/apl-core/pull/2085

feat: look up Gitea pod using selector

---

src/operator/keycloak.ts
src/tasks/keycloak/config.ts
src/tasks/keycloak/realm-factory.ts

This PR adds the sub claim mapper to the admin realm so that the sub property will exist on the api token which is needed for istio to accept the request.

fix: add sub claim mapper to admin realm

---

src/tasks/keycloak/config.ts

This PR fixes client sub claim mapper using user id attribute.
Ticket: https://jira.linode.com/browse/APL-809
PRs: [apl-api](https://github.com/linode/apl-api/pull/747) [apl-console](https://github.com/linode/apl-console/pull/583)

fix: client sub claim mapper
